name: Publish Package to npmjs
on:
  push:
    branches:
      - release
jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Building package
        run: yarn build
      - name: Install semantic-release
        run: yarn global add semantic-release-cli semantic-release
      - run: semantic-release --branches release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
